# -*- coding: utf-8 -*-
"""geojson_to_parquet_for_athena

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14s3SgXSpA7GrFE0MCT_BMczkTjj6RVCq
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install dictor

#https://blog.bigdataboutique.com/2021/04/geospatial-analysis-with-presto-m2nqdw

from geomet import wkt
import json
from dictor import dictor
import os
import pyarrow as pa
import pyarrow.parquet as pq

import pandas as pd

Outputs_Data_Area = "/content/drive/Shareddrives/IDFC Institute Team Drive/World Bank Data/Maharashtra/Data and Methods/Data and supporting info/EDA/outlogic"
with open('/content/drive/Shareddrives/IDFC Institute Team Drive/World Bank Data/Maharashtra/Data and Methods/Data and supporting info/mh_dist.geojson', mode='rb') as f:
  d = json.load(f)

results = []

##For loop pulls only name of admin level 5 
for i in d['features']:
  result = {}
  name = dictor(i,"properties.name")
  type = dictor(i,"geometry.type")
  admin_level = dictor(i,"properties.admin_level")
  geojson = dictor(i, "geometry")
  if type in ['Polygon','MultiPolygon'] and admin_level in ['5']:
    result['name'] = name
    result['coordinates'] = wkt.dumps(geojson,decimals=7)
    results.append(result)
#
data_frame = pd.DataFrame(results)
table = pa.Table.from_pandas(data_frame)

#mh_outlogic_day_data = consolidated_outlogic_df.loc[consolidated_outlogic_df['iso_region'] == 'IN-MH']
Output_File_Name_w_Path=os.path.join(Outputs_Data_Area, "mh_districts_v3.parquet")
data_frame.to_parquet(Output_File_Name_w_Path)

#filesystem = s3fs.S3FileSystem()
#path = "s3://s3-path-here"
#pq.write_to_dataset(table, root_path=path, compression='gzip', filesystem=filesystem)

print(data_frame)